/****************************************************************************/
/**
*
* @file fmsh_psu_parameters.h
*
* This file is automatically generated

* This file contains the address definitions for the hard peripherals
* attached to the FMSH core.
*
*****************************************************************************/

#ifndef _FMSH_PSU_PARAMETERS_H_
#define _FMSH_PSU_PARAMETERS_H_

#include "psu_init.h"

#ifdef __cplusplus
extern "C" {
#endif

/******************* Constant Definitions *********************/
/* System Address Map */
#define VULTURE_SVN_VERSION     3834
#define VULTURE_RELEASE_DATE   "2025/06/20 14:58:50"
#define FPS_DDRMEM_BASEADDR                 (0x00040000)
#define FPS_QSPI0_D_BASEADDR                (0xC0000000)
#define FPS_QSPI1_D_BASEADDR                (0xD0000000)

#define FPS_UART0_BASEADDR                  (0xFF000000)
#define FPS_UART1_BASEADDR                  (0xFF010000)
#define FPS_I2C0_BASEADDR                   (0xFF020000)
#define FPS_I2C1_BASEADDR                   (0xFF030000)
#define FPS_SPI0_BASEADDR                   (0xFF040000)
#define FPS_SPI1_BASEADDR                   (0xFF050000)
#define FPS_CAN0_BASEADDR                   (0xFF060000)
#define FPS_CAN1_BASEADDR                   (0xFF070000)
#define FPS_QSPI0_BASEADDR                  (0xFF090000)
#define FPS_GPIO_BASEADDR                   (0xFF0A0000)
#define FPS_GMAC0_BASEADDR                  (0xFF0B0000)
#define FPS_GMAC1_BASEADDR                  (0xFF0C0000)
#define FPS_GMAC2_BASEADDR                  (0xFF0D0000)
#define FPS_GMAC3_BASEADDR                  (0xFF0E0000)
#define FPS_QSPI1_BASEADDR                  (0xFF0F0000)
#define FPS_NAND_BASEADDR                   (0xFF100000)
#define FPS_TIMER0_BASEADDR                 (0xFF110000)
#define FPS_TIMER1_BASEADDR                 (0xFF120000)
#define FPS_TIMER2_BASEADDR                 (0xFF130000)
#define FPS_TIMER3_BASEADDR                 (0xFF140000)
#define FPS_LPDWDT_BASEADDR                 (0xFF150000)
#define FPS_SDMMC0_BASEADDR                 (0xFF160000)
#define FPS_SDMMC1_BASEADDR                 (0xFF170000)
#define FPS_IOU_SCNTR_BASEADDR              (0xFF250000)
#define FPS_GTC_BASEADDR                    (0xFF260000)
#define FPS_NAND_D_BASEADDR                 (0xFF270000)
#define FPS_LPD_SLCR_BASEADDR               (0xFF410000)
#define FPS_LPD_SLCR_SECURE_BASEADDR        (0xFF4B0000)
#define FPS_PPU_BASEADDR                    (0xFF980000)
#define FPS_PPU_SINK_BASEADDR               (0xFF9C0000)
#define FPS_USB0_BASEADDR                   (0xFF9D0000)
#define FPS_USB1_BASEADDR                   (0xFF9E0000)
#define FPS_AMS_BASEADDR                    (0xFFA50000)
#define FPS_SYSMON_BASEADDR                 (0xFFA50000)
#define FPS_RTC_BASEADDR                    (0xFFA60000)
#define FPS_OCM_MPU_CFG_BASEADDR            (0xFFA70000)
#define FPS_LPD_DMA_BASEADDR                (0xFFB00000)
#define FPS_CSU_BASEADDR                    (0xFFCA0000)
#define FPS_CSUWDT_BASEADDR                 (0xFFCB0000)
#define FPS_BBRAM_BASEADDR                  (0xFFCD0000)
#define FPS_PMU_GLOBAL_BASEADDR             (0xFFD80000)
#define FPS_GIC_BASEADDR                    (0xF9000000)
#define FPS_DDR_MPU0_CFG_BASEADDR           (0xFD000000)
#define FPS_DDR_MPU1_CFG_BASEADDR           (0xFD010000)
#define FPS_DDR_MPU2_CFG_BASEADDR           (0xFD020000)
#define FPS_DDR_MPU3_CFG_BASEADDR           (0xFD030000)
#define FPS_DDR_MPU4_CFG_BASEADDR           (0xFD040000)
#define FPS_DDR_MPU5_CFG_BASEADDR           (0xFD050000)
#define FPS_DDR_MPU6_CFG_BASEADDR           (0xFD060000)
#define FPS_CRF_APB_BASEADDR                (0xFD1A0000)
#define FPS_FPD_DMA_BASEADDR                (0xFD200000)
#define FPS_SMMU_BASEADDR                   (0xFD800000)
#define FPS_FPDWDT_BASEADDR                 (0xFD4D0000)
#define FPS_FPD_MPU_CFG_BASEADDR            (0xFD5D0000)
#define FPS_SMMU_SLCR_BASEADDR              (0xFD5F0000)
#define FPS_FPD_SLCR_BASEADDR               (0xFD610000)
#define FPS_FPD_SLCR_SECURE_BASEADDR        (0xFD690000)
#define FPS_CCI_BASEADDR                    (0xFD900000)
#define FPS_IOU_SLCR_BASEADDR               (0xFF180000)
#define FPS_CRL_APB_BASEADDR                (0xFF5E0000)
#define FPS_CSU_REG_BASEADDR                (0xFFCA0000)

/******************************************************************/

/* Definitions for driver AXIDMAPS */
#define FPAR_AXIDMAPSU_NUM_INSTANCES         (2)
#define FPAR_AXIDMAPSU_NUM_CHANNEL           (8)
#define FPAR_AXIDMAPSU_CHX_OFFSET            (0x10000)

/* Definitions for peripheral DMA */
#define FPAR_AXIDMAPSU_0_DEVICE_ID           (0)
#define FPAR_AXIDMAPSU_0_BASEADDR            (FPS_LPD_DMA_BASEADDR)

/* Definitions for peripheral DMA */
#define FPAR_AXIDMAPSU_1_DEVICE_ID           (1)
#define FPAR_AXIDMAPSU_1_BASEADDR            (FPS_FPD_DMA_BASEADDR)

/******************************************************************/

/* Definitions for driver GPIOPS */
#define FPAR_GPIOPS_NUM_INSTANCES           (6)

/* Definitions for peripheral GPIO */
#define FPAR_GPIOPS_0_DEVICE_ID             (0)
#define FPAR_GPIOPS_0_BASEADDR              (FPS_GPIO_BASEADDR)
#define FPAR_GPIOPS_0_MAXPIN                (26)

#define FPAR_GPIOPS_1_DEVICE_ID             (1)
#define FPAR_GPIOPS_1_BASEADDR              (FPS_GPIO_BASEADDR+0x100)
#define FPAR_GPIOPS_1_MAXPIN                (26)

#define FPAR_GPIOPS_2_DEVICE_ID             (2)
#define FPAR_GPIOPS_2_BASEADDR              (FPS_GPIO_BASEADDR+0x200)
#define FPAR_GPIOPS_2_MAXPIN                (26)

#define FPAR_GPIOPS_3_DEVICE_ID             (3)
#define FPAR_GPIOPS_3_BASEADDR              (FPS_GPIO_BASEADDR+0x300)
#define FPAR_GPIOPS_3_MAXPIN                (32)

#define FPAR_GPIOPS_4_DEVICE_ID             (4)
#define FPAR_GPIOPS_4_BASEADDR              (FPS_GPIO_BASEADDR+0x400)
#define FPAR_GPIOPS_4_MAXPIN                (32)

#define FPAR_GPIOPS_5_DEVICE_ID             (5)
#define FPAR_GPIOPS_5_BASEADDR              (FPS_GPIO_BASEADDR+0x500)
#define FPAR_GPIOPS_5_MAXPIN                (32)

/******************************************************************/

/* Definitions for driver QSPIPSU */
#define FPAR_QSPIPSU_NUM_INSTANCES          (2)

/* Definitions for peripheral PSU_QSPI_0 */
#define FPAR_QSPIPSU_0_DEVICE_ID            (0)
#define FPAR_QSPIPSU_0_BASEADDR             (FPS_QSPI0_BASEADDR)
#define FPAR_QSPIPSU_0_D_BASEADDR           (FPS_QSPI0_D_BASEADDR)
#define FPAR_QSPIPSU_0_CLK_FREQ_HZ          (QSPI_FREQ)
#define FPAR_QSPIPSU_0_BOARD_DELAY          (1.0F)

/* Definitions for peripheral PSU_QSPI_1 */
#define FPAR_QSPIPSU_1_DEVICE_ID            (1)
#define FPAR_QSPIPSU_1_BASEADDR             (FPS_QSPI1_BASEADDR)
#define FPAR_QSPIPSU_1_D_BASEADDR           (FPS_QSPI1_D_BASEADDR)
#define FPAR_QSPIPSU_1_CLK_FREQ_HZ          (QSPI_FREQ)
#define FPAR_QSPIPSU_1_BOARD_DELAY          (1.0F)

/******************************************************************/

/* Definitions for driver NANDPSU */
#define FPAR_NANDPSU_NUM_INSTANCES          (1)

/* Definitions for peripheral PSU_NAND_0 */
#define FPAR_NANDPSU_DEVICE_ID              (0)
#define FPAR_NANDPSU_BASEADDR               (FPS_NAND_BASEADDR)
#define FPAR_NANDPSU_D_BASEADDR             (FPS_NAND_D_BASEADDR)
#define FPAR_NANDPSU_BUS_WIDTH              (8)
#define FPAR_NANDPSU_CLK_FREQ_HZ            (NAND_FREQ)
#define FPAR_NANDPSU_BOARD_DELAY            (1.0F)

/******************************************************************/

/* Definitions for driver SDPSU */
#define FPAR_SDPSU_NUM_INSTANCES            (2)

/* Definitions for peripheral PSU_SD_0 */
#define FPAR_SDPSU_0_DEVICE_ID              (0)
#define FPAR_SDPSU_0_BASEADDR               (FPS_SDMMC0_BASEADDR)
#define FPAR_SDPSU_0_SDIO_CLK_FREQ_HZ       (SDIO0_FREQ)
#define FPAR_SDPSU_0_HAS_CD                 (0)
#define FPAR_SDPSU_0_HAS_WP                 (0)
#define FPAR_SDPSU_0_HAS_BUSPWR             (0)
// 1 for sd2.0/sd3.0, 2 for emmc
#define FPAR_SDPSU_0_TYPE                   (2)
#define FPAR_SDPSU_0_BUSWIDTH               (8)  
#define FPAR_SDPSU_0_INIT_FREQ              (400000)
#define FPAR_SDPSU_0_IS_CACHE_COHERENT      (0)

/* Definitions for peripheral PSU_SD_1 */
#define FPAR_SDPSU_1_DEVICE_ID              (1)
#define FPAR_SDPSU_1_BASEADDR               FPS_SDMMC1_BASEADDR
#define FPAR_SDPSU_1_SDIO_CLK_FREQ_HZ       (SDIO1_FREQ)
#define FPAR_SDPSU_1_HAS_CD                 (0)
#define FPAR_SDPSU_1_HAS_WP                 (0)
#define FPAR_SDPSU_1_HAS_BUSPWR             (0)
// 1 for sd2.0/sd3.0, 2 for emmc
#define FPAR_SDPSU_1_TYPE                   (1)
#define FPAR_SDPSU_1_BUSWIDTH               (8)  
#define FPAR_SDPSU_1_INIT_FREQ              (400000)
#define FPAR_SDPSU_1_IS_CACHE_COHERENT      (0)

/******************************************************************/
/* Definitions for peripheral PS_LPDWDT */
#define FPAR_WDTPS_NUM_INSTANCES            (3)
#define FPAR_LPDWDTPS_DEVICE_ID             (0)
#define FPAR_LPDWDTPS_BASEADDR              (FPS_LPDWDT_BASEADDR)

/* Definitions for peripheral PS_FPDWDT */
#define FPAR_FPDWDTPS_DEVICE_ID             (1)
#define FPAR_FPDWDTPS_BASEADDR              (FPS_FPDWDT_BASEADDR)

/* Definitions for peripheral PS_CSUWDT */
#define FPAR_CSUWDTPS_DEVICE_ID             (2)
#define FPAR_CSUWDTPS_BASEADDR              (FPS_CSUWDT_BASEADDR)

/******************************************************************/
/* Definitions for peripheral PS_RTC */
#define FPAR_RTCPS_NUM_INSTANCES            (1)
#define FPAR_RTCPS_DEVICE_ID                (0)
#define FPAR_RTCPS_BASEADDR                 (FPS_RTC_BASEADDR)

/******************************************************************/

/* Definitions for driver TTCPS */
#define FPAR_TTCPS_NUM_INSTANCES            (4)
/* Definitions for peripheral PS_TTC_0 */
#define FPAR_TTCPS_0_DEVICE_ID              (0)
#define FPAR_TTCPS_0_BASEADDR               (FPS_TIMER0_BASEADDR)
/* Definitions for peripheral PS_TTC_1 */
#define FPAR_TTCPS_1_DEVICE_ID              (1)
#define FPAR_TTCPS_1_BASEADDR               (FPS_TIMER1_BASEADDR)
/* Definitions for peripheral PS_TTC_0 */
#define FPAR_TTCPS_2_DEVICE_ID              (2)
#define FPAR_TTCPS_2_BASEADDR               (FPS_TIMER2_BASEADDR)
/* Definitions for peripheral PS_TTC_1 */
#define FPAR_TTCPS_3_DEVICE_ID              (3)
#define FPAR_TTCPS_3_BASEADDR               (FPS_TIMER3_BASEADDR)

/******************************************************************/

/* Definitions for peripheral PS_GTC */
#define FPAR_GTCPS_NUM_INSTANCES            (2)
#define FPAR_GTCPS_DEVICE_ID                (0)
#define FPAR_GTCPS_BASEADDR                 (FPS_GTC_BASEADDR)
#define FPAR_GTCPS_1_DEVICE_ID              (1)
#define FPAR_GTCPS_1_BASEADDR               (FPS_IOU_SCNTR_BASEADDR)

/******************************************************************/

/* Definitions for driver CANPS */
#define FPAR_CANPS_NUM_INSTANCES            (2)

/* Definitions for peripheral PS_CAN_0 */
#define FPAR_CANPS_0_DEVICE_ID              (0)
#define FPAR_CANPS_0_BASEADDR               (FPS_CAN0_BASEADDR)
#define FPAR_CANPS_0_CAN_CLK_FREQ_HZ        (CAN0_FREQ)
// full_mode = 0,stb_fifo = 1,stb_prio = 2,ptb_mode =3
#define FPAR_CANPS_0_TX_MODE                (ptb_mode)
#define FPAR_CANPS_0_SAMPLE_POINT           (800)
#define FPAR_CANPS_0_D_SAMPLE_POINT         (800)

/* Definitions for peripheral PS_CAN_1 */
#define FPAR_CANPS_1_DEVICE_ID              (1)
#define FPAR_CANPS_1_BASEADDR               (FPS_CAN1_BASEADDR)
#define FPAR_CANPS_1_CAN_CLK_FREQ_HZ        (CAN1_FREQ)
// full_mode = 0,stb_fifo = 1,stb_prio = 2,ptb_mode =3
#define FPAR_CANPS_1_TX_MODE                (ptb_mode)
#define FPAR_CANPS_1_SAMPLE_POINT           (800)
#define FPAR_CANPS_1_D_SAMPLE_POINT         (800)

/******************************************************************/

/* Definitions for driver I2CPS */
#define FPAR_I2CPS_NUM_INSTANCES            (2)

/* Definitions for peripheral PS_I2C_0 */
#define FPAR_I2CPS_0_DEVICE_ID              (0)
#define FPAR_I2CPS_0_BASEADDR               (FPS_I2C0_BASEADDR)
#define FPAR_I2CPS_0_I2C_CLK_FREQ_HZ        (I2C0_FREQ)

/* Definitions for peripheral PS_I2C_1 */
#define FPAR_I2CPS_1_DEVICE_ID              (1)
#define FPAR_I2CPS_1_BASEADDR               (FPS_I2C1_BASEADDR)
#define FPAR_I2CPS_1_I2C_CLK_FREQ_HZ        (I2C1_FREQ)

/******************************************************************/

/* Definitions for driver GPMACPS */
#define FPAR_GMACPS_NUM_INSTANCES           (4)

/* Definitions for peripheral PS_GMAC_0 */
#define FPAR_GMACPS_0_DEVICE_ID             (0)
#define FPAR_GMACPS_0_BASEADDR              (FPS_GMAC0_BASEADDR)
#define FPAR_GMACPS_0_SPEED                 (speed_1000)
#define FPAR_GMACPS_0_INTERFACE             (gmac_path_rgmii)
#define FPAR_GMACPS_0_CACHE_COHERENT    0

/* Definitions for peripheral PS_GMAC_1 */
#define FPAR_GMACPS_1_DEVICE_ID             (1)
#define FPAR_GMACPS_1_BASEADDR              (FPS_GMAC1_BASEADDR)
#define FPAR_GMACPS_1_SPEED                 (speed_1000)
#define FPAR_GMACPS_1_INTERFACE             (gmac_path_gmii)
#define FPAR_GMACPS_1_CACHE_COHERENT    0

/* Definitions for peripheral PS_GMAC_2 */
#define FPAR_GMACPS_2_DEVICE_ID             (2)
#define FPAR_GMACPS_2_BASEADDR              (FPS_GMAC2_BASEADDR)
#define FPAR_GMACPS_2_SPEED                 (speed_1000)
#define FPAR_GMACPS_2_INTERFACE             (gmac_path_sgmii)
#define FPAR_GMACPS_2_CACHE_COHERENT        (0)

/* Definitions for peripheral PS_GMAC_3 */
#define FPAR_GMACPS_3_DEVICE_ID             (3)
#define FPAR_GMACPS_3_BASEADDR              (FPS_GMAC3_BASEADDR)
#define FPAR_GMACPS_3_SPEED                 (speed_1000)
#define FPAR_GMACPS_3_INTERFACE             (gmac_path_rgmii)
#define FPAR_GMACPS_3_CACHE_COHERENT        (0)
/******************************************************************/

/* Definitions for driver UARTPS */
#define FPAR_UARTPS_NUM_INSTANCES           (2)

/* Definitions for peripheral PS_UART_0 */
#define FPAR_UARTPS_0_DEVICE_ID             (0)
#define FPAR_UARTPS_0_BASEADDR              (FPS_UART0_BASEADDR)
#define FPAR_UARTPS_0_UART_CLK_FREQ_HZ      (UART0_FREQ)
#define FPAP_UARTPS_0_HAS_MODEM             (0)

/* Definitions for peripheral PS_UART_1 */
#define FPAR_UARTPS_1_DEVICE_ID             (1)
#define FPAR_UARTPS_1_BASEADDR              (FPS_UART1_BASEADDR)
#define FPAR_UARTPS_1_UART_CLK_FREQ_HZ      (UART1_FREQ)
#define FPAP_UARTPS_1_HAS_MODEM             (0)

/******************************************************************/

/* Definitions for driver USBPS */
#define FPAR_USBPS_NUM_INSTANCES            (2)
/* Definitions for peripheral PS_USB_0 */
#define FPAR_USBPS_0_DEVICE_ID              (0)
#define FPAR_USBPS_0_BASEADDR               (FPS_USB0_BASEADDR)
#define FPAR_USBPS_0_USB_CLK_FREQ_HZ        (USB0_FREQ)
/* Definitions for peripheral PS_USB_1 */
#define FPAR_USBPS_1_DEVICE_ID              (1)
#define FPAR_USBPS_1_BASEADDR               (FPS_USB1_BASEADDR)
#define FPAR_USBPS_1_USB_CLK_FREQ_HZ        (USB1_FREQ)

/******************************************************************/

/* Definitions for driver DEVCPS */
#define FPAR_DEVCPS_NUM_INSTANCES           (1)

/* Definitions for peripheral PS_DEVC */
#define FPAR_DEVCPS_DEVICE_ID               (0)
#define FPAR_DEVCPS_BASEADDR                (FPS_CSU_BASEADDR)
#define FPAR_DEVCPS_DEVC_CLK_FREQ_HZ        (CSU_FREQ)

/******************************************************************/

/* Definitions for driver SYSMONPSU */
#define FPAR_FSYSMONPSU_NUM_INSTANCES       (1)

/* Definitions for peripheral PSU_AMS */
#define FPAR_PSU_AMS_DEVICE_ID              (0)
#define FPAR_PSU_AMS_BASEADDR               (FPS_AMS_BASEADDR)
#define FPAR_PSU_AMS_HIGHADDR               (FPS_AMS_BASEADDR+0xFFFFU)
#define FPAR_PSU_AMS_REF_FREQMHZ            ((float)AMS_FREQ / 1000000)

/* Canonical definitions for peripheral PSU_AMS */
#define FPAR_FSYSMONPSU_0_DEVICE_ID         (FPAR_PSU_AMS_DEVICE_ID)
#define FPAR_FSYSMONPSU_0_BASEADDR          (FPS_SYSMON_BASEADDR)
#define FPAR_FSYSMONPSU_0_HIGHADDR          (FPS_AMS_BASEADDR+0xFFFFU)
#define FPAR_FSYSMONPSU_0_REF_FREQMHZ       ((float)AMS_FREQ / 1000000)

/******************************************************************/

#define FMSH_PUF_INFO_ON_UART               (TRUE)
#define FMSH_PUF_PROGRAM_EFUSE              (TRUE)

/******************************************************************/

/* Definitions for TTC */
#define FPAR_TTCPS_0_TTC_CLK_FREQ_HZ        (TTC0_FREQ)
#define FPAR_TTCPS_1_TTC_CLK_FREQ_HZ        (TTC1_FREQ)
#define FPAR_TTCPS_2_TTC_CLK_FREQ_HZ        (TTC2_FREQ)
#define FPAR_TTCPS_3_TTC_CLK_FREQ_HZ        (TTC3_FREQ)
/******************************************************************/

/* UART print Configuration */
#define STDIN_BASEADDRESS                   FPS_UART1_BASEADDR
#define STDOUT_BASEADDRESS                  FPS_UART1_BASEADDR
#define FPAR_UARTPS_0_BAUDRATE              115200
#define FPAR_UARTPS_1_BAUDRATE              115200

/******************************************************************/

/* Device ID */
#define AXIDMAPS_0_DEVICE_ID    0
#define AXIDMAPS_1_DEVICE_ID    1
#define DDRPS_0_DEVICE_ID       0
#define DEVCFGPS_0_DEVICE_ID    0
#define ENETPS_0_DEVICE_ID       0
#define ENETPS_1_DEVICE_ID       1
#define ENETPS_2_DEVICE_ID       2
#define ENETPS_3_DEVICE_ID       3
#define GTCPS_0_DEVICE_ID       0
#define GTCPS_1_DEVICE_ID       1
#define GPIOPS_0_DEVICE_ID      0
#define GPIOPS_1_DEVICE_ID      1
#define GPIOPS_2_DEVICE_ID      2
#define GPIOPS_3_DEVICE_ID      3
#define GPIOPS_4_DEVICE_ID      4
#define GPIOPS_5_DEVICE_ID      5
#define I2CPS_0_DEVICE_ID      0
#define I2CPS_1_DEVICE_ID      1
#define IPIPS_0_DEVICE_ID       0
#define QSPIPS_0_DEVICE_ID      0
#define RTCPSU_0_DEVICE_ID      0
#define SDMMCPS_0_DEVICE_ID     0
#define SPIPS_1_DEVICE_ID       1
#define TTCPS_0_DEVICE_ID       0
#define TTCPS_1_DEVICE_ID       1
#define TTCPS_2_DEVICE_ID       2
#define TTCPS_3_DEVICE_ID       3
#define UARTPS_0_DEVICE_ID      0
#define UARTPS_1_DEVICE_ID      1
#define WDTPS_0_DEVICE_ID       0
#define WDTPS_1_DEVICE_ID       1
#define WDTPS_2_DEVICE_ID       2

/******************************************************************/

/* GTR */
#define FPAR_GTRPSU_LANE0_PROTOCOL       (0)
#define FPAR_GTRPSU_LANE1_PROTOCOL       (0)
#define FPAR_GTRPSU_LANE2_PROTOCOL       (5)
#define FPAR_GTRPSU_LANE3_PROTOCOL       (5)
#define FPAR_GTRPSU_DP_SPEED             (0)
#define FPAR_GTRPSU_REFCLK0_FREQ_HZ       (GTR_REFCLK0_FREQ)
#define FPAR_GTRPSU_REFCLK1_FREQ_HZ       (GTR_REFCLK1_FREQ)
#define FPAR_GTRPSU_PMA0_SSC_EN     (0)
#define FPAR_GTRPSU_PMA1_SSC_EN     (0)
#define FPAR_PSU_DDRC_0_HAS_ECC     (0)

#ifdef __cplusplus
}
#endif

#endif /* protection macro */
