/***************************************************************************/
/**
*
* @file gtr_init_data.c
*
* This file is automatically generated
*
***************************************************************************/
#include "fmsh_common.h" // common header for all drivers
#include "fmsh_gtr.h"


GTR_Regval gtr_struct1 = {
    .pcie = 0,
    .usb = 0,
    .sata = 0,
    .dp = 0,
    .sgmii = 0,
    .ethernet = 0,
    .pllclk = {0,0,0,0,0,0}, // 0-6 pma0 m0 pll0 clk pma0 m1 pll0 clk pma0
                          // pll1 clk pma1 m0 pll0 clk  pma1 m1 pll0 clk
                          //  pma1  m0 pll1 clkï¼?MHz
    .DSM_fractional = {0,0,0,0,0,0},
    .pll_div = {1,1,1,1,1,1},
    .cmn_offset = {0,0x8000},
    .lane_offset = {0,0x800,0x1000,0x1800},
    .cmn0_pll1_mac = 0,// pll1 macã€?pcieï¼?usb.....6ethernet
    .cmn1_pll1_mac = 0, // pll1 mac
    .fb_div = {0,0,0,0,0,0},    // fbr: 0,dr:1,d32:2

    // phy reg
    .phy_l_mode = {0,0,0,0},
    .lane_icm_cfg = {0,0,0,0},
    .icm_cfg0_reg = 0,
    .icm_cfg1_reg = 0,
    .phy_bfr_en = 1,
    .phy_link_cfg_ln_mode = {0,1,1,1},
    .gtr_cfg_reg = 0x170000,
    .num_standard = 0,
    .pma_xcvr_reg = 0,
    .pma_cmn_clk_reg = 0,
    .phy_pll_cfg = 0x11,
    .phy_pma_pll_raw_ctrl = 0x303,
    // cmn reg
    .cmn0_pll0_dsm_diag_m0 = 0x4004,
    .cmn0_pll0_dsm_diag_m1 = 0x4004,
    .cmn0_pll1_dsm_diag_m0 = 0x4004,
    .cmn1_pll0_dsm_diag_m0 = 0x4004,
    .cmn1_pll0_dsm_diag_m1 = 0x4004,
    .cmn1_pll1_dsm_diag_m0 = 0x4004,

    .cmn0_pdiag_pll0_clk_sel_m0 = 0x601,  // rst val 0x601
    .cmn0_pdiag_pll0_clk_sel_m1 = 0, // rst val 0x400
    .cmn0_pdiag_pll1_clk_sel_m0 = 0,  // rst val 0x400
    .cmn1_pdiag_pll0_clk_sel_m0 = 0x601,
    .cmn1_pdiag_pll0_clk_sel_m1 = 0,
    .cmn1_pdiag_pll1_clk_sel_m0 = 0,

    .cmn0_pdiag_pll0_cp_padj_m0 = 0xb17,
    .cmn0_pdiag_pll0_cp_padj_m1 = 0xb17,
    .cmn0_pdiag_pll1_cp_padj_m0 = 0xb17,
    .cmn1_pdiag_pll0_cp_padj_m0 = 0xb17,
    .cmn1_pdiag_pll0_cp_padj_m1 = 0xb17,
    .cmn1_pdiag_pll1_cp_padj_m0 = 0xb17,

    .cmn0_txpucal_tune = 0,
    .cmn0_txpdcal_tune = 0,
    .cmn1_txpucal_tune = 0,
    .cmn1_txpdcal_tune = 0,

    .cmn0_pll0_vcocal_tctrl = 0x3,
    .cmn0_pll1_vcocal_tctrl = 0x3,
    .cmn1_pll0_vcocal_tctrl = 0x3,
    .cmn1_pll1_vcocal_tctrl = 0x3,
    .cmn_pll_vcocal_init_tmr = {0,0,0,0},
    .cmn_pll_vcocal_iter_tmr = {0,0,0,0},
    .cmn_pll_vcocal_reftim_start = {0xffff,0xffff,0xffff,0xffff},
    .cmn_pll_vcocal_pllcnt_start = {0xffff,0xffff,0xffff,0xffff},

    .cmn_pdiag_pll_ctrl_m = {0x1112,0x1112,0x1112,0x1112,0x1112,0x1112},

    .cmn0_pdiag_pll0_cp_iadj_m0 = 0xe01,
    .cmn0_pdiag_pll0_cp_iadj_m1 = 0xe01,
    .cmn0_pdiag_pll1_cp_iadj_m0 = 0xe01,
    .cmn1_pdiag_pll0_cp_iadj_m0 = 0xe01,
    .cmn1_pdiag_pll0_cp_iadj_m1 = 0xe01,
    .cmn1_pdiag_pll1_cp_iadj_m0 = 0xe01,

    .cmn0_pdiag_pll0_filt_padj_m0 = 0xd05,
    .cmn0_pdiag_pll0_filt_padj_m1 = 0xd05,
    .cmn0_pdiag_pll1_filt_padj_m0 = 0xd05,
    .cmn1_pdiag_pll0_filt_padj_m0 = 0xd05,
    .cmn1_pdiag_pll0_filt_padj_m1 = 0xd05,
    .cmn1_pdiag_pll1_filt_padj_m0 = 0xd05,

    .cmn0_pll0_dsm_fbh_ovrd_m0 = 0xfffc,
    .cmn0_pll0_dsm_fbh_ovrd_m1 = 0xfffc,
    .cmn0_pll1_dsm_fbh_ovrd_m0 = 0xfffc,
    .cmn1_pll0_dsm_fbh_ovrd_m0 = 0xfffc,
    .cmn1_pll0_dsm_fbh_ovrd_m1 = 0xfffc,
    .cmn1_pll1_dsm_fbh_ovrd_m0 = 0xfffc,

    .cmn0_pll0_dsm_fbl_ovrd_m0 = 0xfffc,
    .cmn0_pll0_dsm_fbl_ovrd_m1 = 0xfffc,
    .cmn0_pll1_dsm_fbl_ovrd_m0 = 0xfffc,
    .cmn1_pll0_dsm_fbl_ovrd_m0 = 0xfffc,
    .cmn1_pll0_dsm_fbl_ovrd_m1 = 0xfffc,
    .cmn1_pll1_dsm_fbl_ovrd_m0 = 0xfffc,

    .cmn_pll_intdiv_m = {0,0,0,0,0,0},  // cmn0_pll0_intdiv_m0,cmn0_pll0_intdiv_m1,cmn0_pll1_intdiv_m0,cmn1_pll0_intdiv_m0...
    .cmn_pll_fracdivh_m = {0,0,0,0,0,0}, // cmn0_pll0_fracdivh_m0, cmn0_pll0_fracdivh_m1,
             // cmn0_pll1_fracdivh_m0, cmn1_pll0_fracdivh_m0...
    .cmn_pll_fracdivl_m = {0,0,0,0,0,0},
    .cmn_pll_high_thr_m = {0,0,0,0,0,0}, //  cmn0_pll0_high_thr_m0, cmn0_pll0_high_thr_m1,
             // cmn0_pll1_high_thr_m0, cmn1_pll0_high_thr_m0...

    // different refclk
    .cmn_ssm_bias_tmr = {0,0},

    .cmn_pllsm0_pllpre_tmr = {0,0},
    .cmn_pllsm0_plllock_tmr = {0,0},

    .cmn_pllsm1_pllpre_tmr = {0,0},
    .cmn_pllsm1_plllock_tmr = {0,0},

    .cmn_bgcal_init_tmr = {0,0},
    .cmn_bgcal_iter_tmr = {0,0},

    .cmn_ibcal_init_tmr = {0,0},

    .cmn_txpucal_init_tmr = {0,0},
    .cmn_txpucal_iter_tmr = {0,0},
    .cmn_txpdcal_init_tmr = {0,0},
    .cmn_txpdcal_iter_tmr = {0,0},
    .cmn_rxcal_init_tmr = {0,0},
    .cmn_rxcal_iter_tmr = {0,0},

    .cmn_sd_cal_init_tmr = {0x4,0x4},
    .cmn_sd_cal_iter_tmr = {0,0},
    .cmn_sd_cal_reftim_start = {0xffff,0xffff},
    .cmn_sd_cal_pllcnt_start = {0xffff,0xffff},

    .drv_diag_lane_fcm_en_to = {0,0,0x1f4,0x1f4},
    .drv_diag_lane_fcm_en_mgn_tmr = {0,0,0x96,0x96},

    .rx_sdcal0_init_tmr = {0,0,0x19,0x19},
    .rx_sdcal0_iter_tmr = {0,0,0x7d,0x7d},
    .rx_sdcal1_init_tmr = {0,0,0x19,0x19},
    .rx_sdcal1_iter_tmr = {0,0,0x7d,0x7d},

    .tx_rcvdet_st_tmr = {0,0,0x9c4,0x9c4},

    .cmn_pll_lock_refcnt_start = {0xffff,0xffff,0xffff,0xffff},// cmn0 pll0 cmn0 pll1 cmn1 pll0 cmn1 pll1
    .cmn_pll_lock_pllcnt_start = {0xffff,0xffff,0xffff,0xffff},
    .cmn_pll_lock_pllcnt_thr = {0x3,0x3,0x3,0x3},

    // ssc
    .cmn_pll_ss_ctrl1_m = {0x2,0x2,0x2,0x2,0x2,0x2},
    .cmn_pll_ss_ctrl2_m = {0,0,0,0,0,0},
    .cmn_pll_ss_ctrl3_m = {0,0,0,0,0,0},
    .cmn_pll_ss_ctrl4_m = {0,0,0,0,0,0},
    //mac

    .xcvr_diag_hsclk_div = {0,0,0,0},
    .xcvr_diag_hsclk_sel = {0,0,0,0},
    .xcvr_diag_plldrc_ctrl = {0,0,0,0},

    .tx_txcc_mgnfs_mult_000 = 0,
    .tx_txcc_cpost_mult_00 = 0

  };

