/****************************************************************************/
/**
*
* @file psu_init.h
*
* This file is automatically generated
*
*****************************************************************************/


#define USE_DDR                                                 0x1U
#define DDR_SIZE                                                0x200000000U
#define Effective_DRAM_BUS_Width                                  64U
#define ECC_Enable                                                0U

#ifdef __ICCARM__

/***************************************************************************/

#define PSU_Read(baseAddr)                      \
      (*((volatile uint32_t*)(baseAddr)))
      
#define PSU_ReadReg(baseAddr, offSet)           \
      (*((volatile uint32_t*)((uint32_t)baseAddr + (uint32_t)offSet)))
      
#define PSU_Write(baseAddr, data)               \
      (*((volatile uint32_t*)(baseAddr)) = (uint32_t)data)
      
#define PSU_WriteReg(baseAddr, offSet, data)    \
      ((*((volatile uint32_t *)((uint32_t)baseAddr + (uint32_t)offSet))) = (uint32_t)data)
      
#define PSU_WritePubReg(baseAddr, offSet, data)  \
      (*((volatile uint32_t *)((uint32_t)baseAddr + (uint32_t)(offSet<<2))) = (uint16_t)data)
      
/***************************************************************************/
#define CRF_APB                                                 0xFD1A0000U
#define DDR4_CTL_BASEADDR                                       0xFD070000U
#define DDR4_PUB_BASEADDR                                       0xF4000000U

#define CRF_WPROT                                               0x1CU
#define RST_DDR_SS                                              0x108U

#define UctWriteProtShadow                                      0x340010U
#define DctWriteOnly                                            0x3400C0U
#define DctWriteProt                                            0x3400C4U
#define UctWriteOnlyShadow                                      0x3400C8U
#define UctDatWriteOnlyShadow                                   0x3400D0U
#define CALBUSY                                                 0x8025CU

/***************************************************************************/
/* Clock Frequency */
#define PSU_CLK_FREQ  33330000U

#define RPU_FREQ       599940000U
#define QSPI_FREQ       49995000U
#define NAND_FREQ       100000000U
#define SDIO0_FREQ       199980000U
#define SDIO1_FREQ       100000000U
#define UART0_FREQ       99990000U
#define UART1_FREQ       99990000U
#define SPI0_FREQ       100000000U
#define SPI1_FREQ       199980000U
#define I2C0_FREQ       99990000U
#define I2C1_FREQ       99990000U
#define CAN0_FREQ       100000000U
#define CAN1_FREQ       100000000U
#define CSU_FREQ       99990000U
#define LPD_SWDT_FREQ       100000000U
#define TTC0_FREQ       100000000U
#define TTC1_FREQ       100000000U
#define TTC2_FREQ       100000000U
#define TTC3_FREQ       100000000U
#define GTC_FREQ       99990000U
#define AMS_FREQ       59994000U
#define APU_FREQ       1199880000U
#define DDR_FREQ       533280000U
#define VPU_FREQ       799920000U
#define GPU_FREQ       799920000U
#define USB0_FREQ       100000000U
#define USB1_FREQ       100000000U
#define USB_SOF_FREQ       100000000U
#define ENET0_FREQ       124987500U
#define ENET1_FREQ       124987500U
#define ENET2_FREQ       124987500U
#define ENET3_FREQ       124987500U
#define GEM_TSU_FREQ       249975000U
#define FPD_SWDT_FREQ       100000000U
#define GTR_REFCLK0_FREQ       0U
#define GTR_REFCLK1_FREQ       0U

/***************************************************************************/
/* Status */
#define PSU_INIT_SUCCESS                                        (0)
#define PSU_INIT_FAIL                                           (1)
#define PSU_INIT_TIMEOUT                                        (2)

#define PSU_MASK_POLL_TIME                                      (500000000)

/***************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif

void ddr_controller_init_data();
void ddr_pub_init_data_0();
void ddr_pub_init_data_1();

int psu_init();
int psu_init_ddr_self_refresh();
int psu_protection();
unsigned long psu_ps_pl_reset_config_data();
unsigned long psu_ps_pl_isolation_removal_data();
int psu_init_for_pm();

#ifdef __cplusplus
}
#endif

#endif

