// parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits"
// parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits"

/**********************************************************************
 * __LICENCE_BODY_COPYRIGHT__
 * __LICENCE_BODY_CADENCE__
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_USBSSP_REGS_H_
#define REG_USBSSP_REGS_H_

#include "cps_drv.h"

#include "usbssp_regs_macros.h"

typedef struct __attribute__((packed)) USBSSP_Regs_s {
    volatile uint32_t CDNS_DID;
    volatile uint32_t CDNS_RID;
    volatile uint32_t CDNS_CFGS1;
    volatile uint32_t CDNS_CFGS2;
    volatile uint32_t OTGCMD;
    volatile uint32_t OTGSTS;
    volatile uint32_t OTGSTATE;
    volatile uint32_t OTGIEN;
    volatile uint32_t OTGIVECT;
    volatile uint32_t OTGTMR;
    volatile uint32_t OTGSIMULATE;
    volatile uint32_t ADPBC_STS;
    volatile uint32_t ADP_RAMP_TIME;
    volatile uint32_t ADPBC_CTRL1;
    volatile uint32_t ADPBC_CTRL2;
    volatile uint32_t PORT_OVERRIDE;
    volatile uint32_t VBUSVALID_DBNC_CFG;
    volatile uint32_t SESSVALID_DBNC_CFG;
    volatile uint32_t SUSP_TIMING_CTRL;
    volatile uint32_t SUPP_PAGESIZE;
    volatile uint32_t SYS_PAGESIZE;
    volatile uint32_t PBAR0;
    volatile char pad__0[0x28U];
} USBSSP_Regs;

#endif /* REG_USBSSP_REGS_H_ */

// parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits"
// parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits"
