
/******************************************************************************
 *
 * Copyright (C) FMSH, Corp.  All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * FMSH BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
 * OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * Except as contained in this notice, the name of the FMSH shall not be used
 * in advertising or otherwise to promote the sale, use or other dealings in
 * this Software without prior written authorization from FMSH.
 *
 ******************************************************************************/

// #include "xparameters.h"
#include "fmsh_ipi.h"

/*
 * The configuration table for devices
 */
IpiPsu_Config IpiPsu_ConfigTable[PAR_IPIPSU_NUM_INSTANCES] = {

    {PAR_PSU_IPI_0_DEVICE_ID,
     PAR_PSU_IPI_0_S_AXI_BASEADDR,
     PAR_PSU_IPI_0_BIT_MASK,
     PAR_PSU_IPI_0_BUFFER_INDEX,
     PAR_PSU_IPI_0_INT_ID,
     PAR_IPIPSU_NUM_TARGETS,
     {

         {PAR_PSU_IPI_0_BIT_MASK, PAR_PSU_IPI_0_BUFFER_INDEX},
         {PAR_PSU_IPI_1_BIT_MASK, PAR_PSU_IPI_1_BUFFER_INDEX},
         {PAR_PSU_IPI_2_BIT_MASK, PAR_PSU_IPI_2_BUFFER_INDEX},
         {PAR_PSU_IPI_3_BIT_MASK, PAR_PSU_IPI_3_BUFFER_INDEX},
         {PAR_PSU_IPI_4_BIT_MASK, PAR_PSU_IPI_4_BUFFER_INDEX},
         {PAR_PSU_IPI_5_BIT_MASK, PAR_PSU_IPI_5_BUFFER_INDEX},
         {PAR_PSU_IPI_6_BIT_MASK, PAR_PSU_IPI_6_BUFFER_INDEX},
         {PAR_PSU_IPI_7_BIT_MASK, PAR_PSU_IPI_7_BUFFER_INDEX},
         {PAR_PSU_IPI_8_BIT_MASK, PAR_PSU_IPI_8_BUFFER_INDEX},
         {PAR_PSU_IPI_9_BIT_MASK, PAR_PSU_IPI_9_BUFFER_INDEX},
         {PAR_PSU_IPI_10_BIT_MASK, PAR_PSU_IPI_10_BUFFER_INDEX}}},
    {PAR_PSU_IPI_1_DEVICE_ID,
     PAR_PSU_IPI_1_S_AXI_BASEADDR,
     PAR_PSU_IPI_1_BIT_MASK,
     PAR_PSU_IPI_1_BUFFER_INDEX,
     PAR_PSU_IPI_1_INT_ID,
     PAR_IPIPSU_NUM_TARGETS,
     {

         {PAR_PSU_IPI_0_BIT_MASK, PAR_PSU_IPI_0_BUFFER_INDEX},
         {PAR_PSU_IPI_1_BIT_MASK, PAR_PSU_IPI_1_BUFFER_INDEX},
         {PAR_PSU_IPI_2_BIT_MASK, PAR_PSU_IPI_2_BUFFER_INDEX},
         {PAR_PSU_IPI_3_BIT_MASK, PAR_PSU_IPI_3_BUFFER_INDEX},
         {PAR_PSU_IPI_4_BIT_MASK, PAR_PSU_IPI_4_BUFFER_INDEX},
         {PAR_PSU_IPI_5_BIT_MASK, PAR_PSU_IPI_5_BUFFER_INDEX},
         {PAR_PSU_IPI_6_BIT_MASK, PAR_PSU_IPI_6_BUFFER_INDEX},
         {PAR_PSU_IPI_7_BIT_MASK, PAR_PSU_IPI_7_BUFFER_INDEX},
         {PAR_PSU_IPI_8_BIT_MASK, PAR_PSU_IPI_8_BUFFER_INDEX},
         {PAR_PSU_IPI_9_BIT_MASK, PAR_PSU_IPI_9_BUFFER_INDEX},
         {PAR_PSU_IPI_10_BIT_MASK, PAR_PSU_IPI_10_BUFFER_INDEX}}},
    {PAR_PSU_IPI_2_DEVICE_ID,
     PAR_PSU_IPI_2_S_AXI_BASEADDR,
     PAR_PSU_IPI_2_BIT_MASK,
     PAR_PSU_IPI_2_BUFFER_INDEX,
     PAR_PSU_IPI_2_INT_ID,
     PAR_IPIPSU_NUM_TARGETS,
     {

         {PAR_PSU_IPI_0_BIT_MASK, PAR_PSU_IPI_0_BUFFER_INDEX},
         {PAR_PSU_IPI_1_BIT_MASK, PAR_PSU_IPI_1_BUFFER_INDEX},
         {PAR_PSU_IPI_2_BIT_MASK, PAR_PSU_IPI_2_BUFFER_INDEX},
         {PAR_PSU_IPI_3_BIT_MASK, PAR_PSU_IPI_3_BUFFER_INDEX},
         {PAR_PSU_IPI_4_BIT_MASK, PAR_PSU_IPI_4_BUFFER_INDEX},
         {PAR_PSU_IPI_5_BIT_MASK, PAR_PSU_IPI_5_BUFFER_INDEX},
         {PAR_PSU_IPI_6_BIT_MASK, PAR_PSU_IPI_6_BUFFER_INDEX},
         {PAR_PSU_IPI_7_BIT_MASK, PAR_PSU_IPI_7_BUFFER_INDEX},
         {PAR_PSU_IPI_8_BIT_MASK, PAR_PSU_IPI_8_BUFFER_INDEX},
         {PAR_PSU_IPI_9_BIT_MASK, PAR_PSU_IPI_9_BUFFER_INDEX},
         {PAR_PSU_IPI_10_BIT_MASK, PAR_PSU_IPI_10_BUFFER_INDEX}}},
    {PAR_PSU_IPI_7_DEVICE_ID,
     PAR_PSU_IPI_7_S_AXI_BASEADDR,
     PAR_PSU_IPI_7_BIT_MASK,
     PAR_PSU_IPI_7_BUFFER_INDEX,
     PAR_PSU_IPI_7_INT_ID,
     PAR_IPIPSU_NUM_TARGETS,
     {

         {PAR_PSU_IPI_0_BIT_MASK, PAR_PSU_IPI_0_BUFFER_INDEX},
         {PAR_PSU_IPI_1_BIT_MASK, PAR_PSU_IPI_1_BUFFER_INDEX},
         {PAR_PSU_IPI_2_BIT_MASK, PAR_PSU_IPI_2_BUFFER_INDEX},
         {PAR_PSU_IPI_3_BIT_MASK, PAR_PSU_IPI_3_BUFFER_INDEX},
         {PAR_PSU_IPI_4_BIT_MASK, PAR_PSU_IPI_4_BUFFER_INDEX},
         {PAR_PSU_IPI_5_BIT_MASK, PAR_PSU_IPI_5_BUFFER_INDEX},
         {PAR_PSU_IPI_6_BIT_MASK, PAR_PSU_IPI_6_BUFFER_INDEX},
         {PAR_PSU_IPI_7_BIT_MASK, PAR_PSU_IPI_7_BUFFER_INDEX},
         {PAR_PSU_IPI_8_BIT_MASK, PAR_PSU_IPI_8_BUFFER_INDEX},
         {PAR_PSU_IPI_9_BIT_MASK, PAR_PSU_IPI_9_BUFFER_INDEX},
         {PAR_PSU_IPI_10_BIT_MASK, PAR_PSU_IPI_10_BUFFER_INDEX}}},
    {PAR_PSU_IPI_8_DEVICE_ID,
     PAR_PSU_IPI_8_S_AXI_BASEADDR,
     PAR_PSU_IPI_8_BIT_MASK,
     PAR_PSU_IPI_8_BUFFER_INDEX,
     PAR_PSU_IPI_8_INT_ID,
     PAR_IPIPSU_NUM_TARGETS,
     {

         {PAR_PSU_IPI_0_BIT_MASK, PAR_PSU_IPI_0_BUFFER_INDEX},
         {PAR_PSU_IPI_1_BIT_MASK, PAR_PSU_IPI_1_BUFFER_INDEX},
         {PAR_PSU_IPI_2_BIT_MASK, PAR_PSU_IPI_2_BUFFER_INDEX},
         {PAR_PSU_IPI_3_BIT_MASK, PAR_PSU_IPI_3_BUFFER_INDEX},
         {PAR_PSU_IPI_4_BIT_MASK, PAR_PSU_IPI_4_BUFFER_INDEX},
         {PAR_PSU_IPI_5_BIT_MASK, PAR_PSU_IPI_5_BUFFER_INDEX},
         {PAR_PSU_IPI_6_BIT_MASK, PAR_PSU_IPI_6_BUFFER_INDEX},
         {PAR_PSU_IPI_7_BIT_MASK, PAR_PSU_IPI_7_BUFFER_INDEX},
         {PAR_PSU_IPI_8_BIT_MASK, PAR_PSU_IPI_8_BUFFER_INDEX},
         {PAR_PSU_IPI_9_BIT_MASK, PAR_PSU_IPI_9_BUFFER_INDEX},
         {PAR_PSU_IPI_10_BIT_MASK, PAR_PSU_IPI_10_BUFFER_INDEX}}},
    {PAR_PSU_IPI_9_DEVICE_ID,
     PAR_PSU_IPI_9_S_AXI_BASEADDR,
     PAR_PSU_IPI_9_BIT_MASK,
     PAR_PSU_IPI_9_BUFFER_INDEX,
     PAR_PSU_IPI_9_INT_ID,
     PAR_IPIPSU_NUM_TARGETS,
     {

         {PAR_PSU_IPI_0_BIT_MASK, PAR_PSU_IPI_0_BUFFER_INDEX},
         {PAR_PSU_IPI_1_BIT_MASK, PAR_PSU_IPI_1_BUFFER_INDEX},
         {PAR_PSU_IPI_2_BIT_MASK, PAR_PSU_IPI_2_BUFFER_INDEX},
         {PAR_PSU_IPI_3_BIT_MASK, PAR_PSU_IPI_3_BUFFER_INDEX},
         {PAR_PSU_IPI_4_BIT_MASK, PAR_PSU_IPI_4_BUFFER_INDEX},
         {PAR_PSU_IPI_5_BIT_MASK, PAR_PSU_IPI_5_BUFFER_INDEX},
         {PAR_PSU_IPI_6_BIT_MASK, PAR_PSU_IPI_6_BUFFER_INDEX},
         {PAR_PSU_IPI_7_BIT_MASK, PAR_PSU_IPI_7_BUFFER_INDEX},
         {PAR_PSU_IPI_8_BIT_MASK, PAR_PSU_IPI_8_BUFFER_INDEX},
         {PAR_PSU_IPI_9_BIT_MASK, PAR_PSU_IPI_9_BUFFER_INDEX},
         {PAR_PSU_IPI_10_BIT_MASK, PAR_PSU_IPI_10_BUFFER_INDEX}}},
    {PAR_PSU_IPI_10_DEVICE_ID,
     PAR_PSU_IPI_10_S_AXI_BASEADDR,
     PAR_PSU_IPI_10_BIT_MASK,
     PAR_PSU_IPI_10_BUFFER_INDEX,
     PAR_PSU_IPI_10_INT_ID,
     PAR_IPIPSU_NUM_TARGETS,
     {

         {PAR_PSU_IPI_0_BIT_MASK, PAR_PSU_IPI_0_BUFFER_INDEX},
         {PAR_PSU_IPI_1_BIT_MASK, PAR_PSU_IPI_1_BUFFER_INDEX},
         {PAR_PSU_IPI_2_BIT_MASK, PAR_PSU_IPI_2_BUFFER_INDEX},
         {PAR_PSU_IPI_3_BIT_MASK, PAR_PSU_IPI_3_BUFFER_INDEX},
         {PAR_PSU_IPI_4_BIT_MASK, PAR_PSU_IPI_4_BUFFER_INDEX},
         {PAR_PSU_IPI_5_BIT_MASK, PAR_PSU_IPI_5_BUFFER_INDEX},
         {PAR_PSU_IPI_6_BIT_MASK, PAR_PSU_IPI_6_BUFFER_INDEX},
         {PAR_PSU_IPI_7_BIT_MASK, PAR_PSU_IPI_7_BUFFER_INDEX},
         {PAR_PSU_IPI_8_BIT_MASK, PAR_PSU_IPI_8_BUFFER_INDEX},
         {PAR_PSU_IPI_9_BIT_MASK, PAR_PSU_IPI_9_BUFFER_INDEX},
         {PAR_PSU_IPI_10_BIT_MASK, PAR_PSU_IPI_10_BUFFER_INDEX}}}};
